apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: christoli/udagram-api-feed:v3e
        ports:
        - containerPort: 8080